services:
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha123
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql

